version: '{build}'
image: Visual Studio 2017
clone_depth: 1
build_script:
- ps: >-
    mkdir builds
    
    cd builds
    
    mkdir x86
    
    cd x86
    
    cmake ../.. -T v141_xp
    
    cmake --build . --config RelWithDebInfo
    
    cd ..
    
    mkdir x64
    
    cd x64
    
    cmake ../.. -A x64
    
    cmake --build . --config RelWithDebInfo
    
    cd ..
    
    7z a eu07_x86_bin.zip ./x86/bin/RelWithDebInfo/*.exe
    
    7z a eu07_x86_pdb.zip ./x86/pdb/RelWithDebInfo/*.pdb
    
    7z a eu07_x64_bin.zip ./x64/bin/RelWithDebInfo/*.exe
    
    7z a eu07_x64_pdb.zip ./x64/pdb/RelWithDebInfo/*.pdb
test: off
deploy: off
artifacts:
- path: builds/eu07_x86_bin.zip
  name: binaries_x86
- path: builds/eu07_x64_bin.zip
  name: binaries_x64
- path: builds/eu07_x86_pdb.zip
  name: symbols_x86
- path: builds/eu07_x64_pdb.zip
  name: symbols_x64
